### ISSUE TITLE
dirty gap minder data

### ISSUE THREAD

**Issue by nerdcommander** [Reproducible-Science-Curriculum/data-exploration-RR-Jupyter#1]
https://github.com/STAT545-UBC/STAT545-UBC.github.io/blob/master/gapminderDataFiveYear_dirty.txt

**Comment by kellieotto** [comment]
Make it more dirty!

**Comment by kellieotto** [comment]
Make mistakes in the top 5 rows

**Comment by clarasorensen** [comment]
dirtier data set (added missing values, repeated values, added a space between 'lifeExp' column name): [DirtyData](https://github.com/Reproducible-Science-Curriculum/data-exploration-RR-Jupyter/blob/master/gapminderDataFiveYear_dirty.txt)
