### ISSUE TITLE
Handling Missing Data

### ISSUE THREAD

**Issue by clarasorensen** [Reproducible-Science-Curriculum/data-exploration-RR-Jupyter#11]
We need to add a discussion about the pros/cons of dropping "missing data" as well as a bit more about what we mean by missing data

**Comment by clarasorensen** [comment]
Missing data is an important issue to handle. Ignoring it doesn't make it go away. There are different ways of dealing with missing data which include:
1. analyzing only the available data (i.e. ignore the missing data)
2. input the missing data with replacement values and treating these as though they were observed
3. input the missing data and account for the fact that these were inputed with uncertainty (ex: create a new boolean variable so you know that these values were not actually observed)
4. use statistical models to allow for missing data--make assumptions about their relationships with the available data as necessary

For our purposes with the dirty gapminder data set, we know our missing data is excess (and unnecessary) and we are going to choose to analyze only the available data. To do this, we will simply remove rows with missing values.

This is incredibly easy to do because pandas allows you to either remove all instances will null data or replace them with a particular value.
df = df.dropna() drops rows with any column having NA/null data

df = df.fillna(value) replaces all NA/null data with the argument value.

**Comment by kellieotto** [comment]
added
