### ISSUE TITLE
elementary plotting

### ISSUE THREAD

**Issue by nhejazi** [Reproducible-Science-Curriculum/data-exploration-RR-Jupyter#14]
## Visualization with `matplotlib`

Recall that [matplotlib](http://matplotlib.org) is Python's main visualization 
library. It provides a range of tools for constructing plots, and numerous 
high-level plotting libraries (e.g., [seaborn](http://seaborn.pydata.org)) are 
built with matplotlib in mind. When we were in the early stages of setting up 
our analysis, we loaded these libraries like so:

```Python
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
```

_Consider the above three commands to be essential practice for plotting (as
essential as `import pandas as pd` is for data munging)._

Now, let's turn to data visualization. In order to get a feel for the properties
of the data set we are working with, data visualization is key. While, we will
focus only on the essentials of how to properly construct plots in univariate
and bivariate settings here, it's worth noting that both matplotlib and seaborn
support a diversity of plots: [matplotlib 
gallery](http://matplotlib.org/gallery.html), [seaborn
gallery](http://seaborn.pydata.org/examples/). 

---

### Single variables

* __Histograms__ - provide a quick way of visualizing the distribution of numerical
  data, or the frequencies of observations for categorical variables.

```Python
# example plot goes here
```

* __Boxplots__ - provide a way of comparing the summary measures (e.g., max, min,
  quartiles) across variables in a data set.

```Python
# example plot goes here
```

---

### Pairs of variables

* __Scatterplots__ - visualization of relationships across two variables...

```Python
# example plot goes here
```

* ...

```Python
# example plot goes here
```

---

### Why use `seaborn`?

As noted above, seaborn is a high-level plotting library for statistical data 
visualization. In addition to simplifying plotting, it also provides facilities 
for customizing matplotlib plots (accessible via `sns.set()`).

**Comment by kellieotto** [comment]
added
