### ISSUE TITLE
summaries code and minimal narrative

### ISSUE THREAD

**Issue by nerdcommander** [Reproducible-Science-Curriculum/data-exploration-RR-Jupyter#15]
# Summarizing data
Remember that the `info()` method gives a few useful pieces of information, including the shape of the dataframe, the variable type of each column, and the amount of memory stored. We can see many of our changes (continent and country columns instead of region, higher number of rows, etc.) reflected in the output of the `info()` method.

`gapminder_comb.info()`

We also saw above that the `describe()` method will take the numeric columns and give a summary of their values. We have to remember that we changed the changed column names, and this time it shouldn't have NAs.

`gapminder_comb[['pop', 'lifeexp', 'gdppercap']].describe()`

### more summaries

what if we just want a single value, like the mean of the population? We can call mean on a single column this way:

`gapminder_comb['pop'].mean()`

What if we want to know the mean population by _continent_? Then we need to use the Pandas `groupby()` method and tell it which column we want to group by.

`gapminder_comb[['continent', 'pop']].groupby(by='continent').mean()`

What if we want to know the mean population by continent?

`gapminder_comb[['continent', 'pop']].groupby(by='continent').median()`

Or the number of entries (rows) per continent?

`gapminder_comb[['continent', 'country']].groupby(by='continent').count()`

Sometimes we don't want a whole data frame. Here is another way to do this that produces a series as opposed to a data frame that tells us number of entries (rows). 

`gapminder_comb[['continent', 'country']].groupby(by='continent').size()`

We can also look at the mean GDP per capita of each country: 

`gapminder_comb[['country', 'gdppercap']].groupby(by='country').mean().head(12)`

What if we wanted a new data frame that just contained these summaries? This could be a table in a report, for example.

`continent_mean_pop = gapminder_comb[['continent', 'pop']].groupby(by='continent').mean()
continent_mean_pop = continent_mean_pop.rename(columns = {'pop':'meanpop'})
continent_row_ct = gapminder_comb[['continent', 'country']].groupby(by='continent').count()
continent_row_ct = continent_row_ct.rename(columns = {'country':'nrows'})
continent_median_pop = gapminder_comb[['continent', 'pop']].groupby(by='continent').median()
continent_median_pop = continent_median_pop.rename(columns = {'pop':'medianpop'})
gapminder_summs = pd.concat([continent_row_ct,continent_mean_pop,continent_median_pop], axis=1)
gapminder_summs = gapminder_summs.rename(columns = {'y':'year'})
gapminder_summs`

**Comment by kellieotto** [comment]
Added
