### ISSUE TITLE
reset_index()

### ISSUE THREAD

**Issue by kellieotto** [Reproducible-Science-Curriculum/data-exploration-RR-Jupyter#5]
Need narrative and code for this feature, after dropping NAs and dropping duplicates

**Comment by clarasorensen** [comment]
There's a little bit about this in the "Handling (Unwanted) Repetitive Data" when it's first used but we can add a bit-- 

## Reindexing with reset_index()
Now we have 1704 rows, but our indexes are off. We can reset our indices easily with the call reset_index(drop=True). Remember, Python is 0-indexed so our indices will be valued 0-1703.

The concept of reindexing is important. When we removed some of the messier, unwanted data, we had "gaps" in our index values. By correcting this, we can improve our search functionality and our ability to perform iterative functions on our cleaned data set.

**Comment by kellieotto** [comment]
added

**Comment by JamiesHQ** [comment]
@kellieotto @clarasorensen : updating the lesson this weekend- can this issue be closed? thx!

**Comment by kellieotto** [comment]
I read through that section of the lesson and I believe we addressed it.

**Comment by JamiesHQ** [comment]
thanks @kellieotto
